Expo camera
rice-apps/hmns pull request #7
Opened 2023-10-28 20:55 UTC by yuxuan-xue67

We created an expo camera that can take photo and save the photo to the camera roll.

2023-10-28 20:59 UTC, DanielCufino requested changes
Please see slack chanell message about running the Linter

2023-11-11 19:41 UTC, DanielCufino approved these changes, later dismissed
Everything looks good. Great work!

2023-11-11 19:43 UTC, victor-xie submitted a review, later dismissed

2023-11-11 19:45 UTC, victor-xie approved these changes

2023-11-11 19:45 UTC, merged